<ButtonItem>:
  value: ""
  height: 60
  size_hint_y: None
  BoxLayout:
    orientation: "horizontal"
    Button:
      size_hint_x: None
      width: self.height
      font_name: "fonts/Font Awesome 6 Free-Solid-900.otf"
      font_size: 21
      text: "\uf129"
    Label:
      size_hint_x: 0.7
      text: root.name
    Button:
      size_hint_x: None
      width: 250
      text: str(root.value)
      on_release: root.dispatch_release()